// <auto-generated />
namespace testbiedro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class dupa25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dupa25));
        
        string IMigrationMetadata.Id
        {
            get { return "201701302310280_dupa25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
